export const PROJECTS = [
    {
        title: "Gesture Blur Camera",
        image: "/images/projects/gesture-blur.png",
        translationKey: "gestureblur",
        technologies: ["Next.js", "TypeScript", "Tailwind CSS", "MediaPipe", "AI", "Vercel"],
        role: "Fullstack & AI Developer",
        liveUrl: "https://gesture-blur-camera.rendyachmad.my.id/",
    },
    {
        title: "Masjid Al Firdaus",
        image: "/images/projects/alfirdaus-dashboard.png",
        translationKey: "alfirdaus",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Tailwind CSS", "Rest API"],
        role: "Fullstack Developer",
        liveUrl: "https://github.com/RndyAchmad/sim-masjid-al-firdaus",
    },
    {
        title: "Olimportal",
        image: "/images/projects/olimportal.png",
        translationKey: "olimportal",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Tailwind CSS", "Datatables", "Guzzle", "Instagram Graph API"],
        role: "Fullstack Developer",
    },
    {
        title: "FUOMO",
        image: "/images/projects/fuomo-desktop.jpeg",
        translationKey: "fuomo",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Sass", "Redis"],
        role: "Backend Developer",
        liveUrl: "https://fuomo.id",
    },
    {
        title: "ETS",
        image: "/images/projects/ordo-dashboard.jpeg",
        translationKey: "ets",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Sass"],
        role: "Backend Developer",
        liveUrl: "https://github.com/RndyAchmad/ets-mentoring",
    },
    {
        title: "Xymart",
        image: "/images/projects/xymart-dashboard.jpeg",
        translationKey: "xymart",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Sass"],
        role: "Backend Developer",
    },
    {
        title: "Proton",
        image: "/images/projects/proton-dashboard.jpeg",
        translationKey: "proton",
        technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Jquery", "Ajax", "Sass"],
        role: "Backend Developer",
    },
    {
        title: "DWO",
        image: "/images/projects/dwo1.jpeg",
        translationKey: "dwo",
        technologies: ["Laravel", "Livewire", "Volt", "Alpine.js", "PHP", "MySQL", "JavaScript"],
        role: "Backend Developer",
        liveUrl: "https://github.com/RndyAchmad/dashboard-dwo",
    },
    {
        title: "Solemate",
        image: "/images/projects/solemate.png",
        translationKey: "solemate",
        technologies: ["Flutter", "Dart", "Firebase"],
        role: "Mobile Developer",
        liveUrl: "https://github.com/RndyAchmad/solemate"
    }
];